### ISSUE TITLE
preg_match(): Compilation failed: regular expression is too large at offset 156184

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-validator#8] opened 2019-12-31 22:33 UTC
This happens while using `Zend\Validator\Hostname->isValid('tapi4457@hsoqvf.biz')` because hostname/Biz.php contains enormous regular expression

Trace looks like this:

preg_match('/^[\\x{002d}0-9a-z\\x{3447}\\x{3473}\\x{359..(156088 chars skipped)..9FA0}\\x{9FA2}\\x{9FA4}\\x{9FA5}]{1,20}$/iu','tapi4457@hsoqvf')
  /vendor/zendframework/zend-validator/src/Hostname.php:1877

PHP Version 7.1.7

---

Originally posted by @ac-dc at https://github.com/zendframework/zend-validator/issues/219

**Comment by samsonasik** [comment] 2020-07-16 11:44
I can't reproduce the compilation error with latest laminas-validator: 

```bash
➜  laminas-validator git:(master) php -a
Interactive shell

php > include 'vendor/autoload.php';

php > var_dump((new Laminas\Validator\Hostname())->isValid('tapi4457@hsoqvf.biz'));
php shell code:1:
bool(false)
```

I'm closing it.

**Comment by Thaix** [comment] 2020-08-13 13:46
That’s strange, the same test on my machine leads to the warning mentioned above:

```
php > include 'vendor/autoload.php';
php > var_dump((new Laminas\Validator\Hostname())->isValid('tapi4457@hsoqvf.biz'));
PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 156184 in /home/apidev/current/vendor/laminas/laminas-validator/src/Hostname.php on line 2104
bool(false)
```
`"name": "laminas/laminas-validator", "version": "2.13.4",`

PHP Version: 
```
PHP 7.4.7 (cli) (built: Jun 12 2020 07:48:26) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies
```

**Comment by samsonasik** [comment] 2020-08-13 14:39
ok, reopen it.

**Comment by bcremer** [comment] 2020-08-13 14:55
@Thaix @samsonasik this issue might be depended on the pcre limits

Could you both please post the results of your php configuration here:

```
php -i | grep pcre | grep imit   
pcre.backtrack_limit => 1000000 => 1000000
pcre.recursion_limit => 100000 => 100000
```

**Comment by samsonasik** [comment] 2020-08-14 06:04
It seems the compilation error too larget because of big regex at  https://github.com/laminas/laminas-validator/blob/96529e873a6eaca7edf097c5130414e9ff7ec3ea/src/Hostname/Biz.php#L25-L2901

**Comment by weierophinney** [comment] 2020-08-14 14:21
Verified as well. Defaults for both INI values are 100000, as it turns out. I tried bumping each to 1000000, and still hit the limits.

We're either going to need a separate validation for `.biz` domains, or have somebody with good PCRE knowledge audit and simplify our regex.

**Comment by samsonasik** [comment] 2020-08-14 14:37
For quick fix, probably just check if string has "@" character...

**Comment by samsonasik** [comment] 2020-08-14 14:41
I created PR https://github.com/laminas/laminas-validator/pull/67 for possible fix by handle if hostname has `@` character

**Closed** 2021-01-06 15:07 UTC
Labels: Bug, Help Wanted
